"""add_payment_fields_to_appointments

Revision ID: 2658b13a1641
Revises: c3d4e5f6a7b8
Create Date: 2026-01-06 09:02:00.008655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2658b13a1641'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_screenshot_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_verification_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_verified_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_verification_notes', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['reference_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('payment_verification_notes')
        batch_op.drop_column('payment_verified_by')
        batch_op.drop_column('payment_verified_at')
        batch_op.drop_column('payment_verification_status')
        batch_op.drop_column('payment_amount')
        batch_op.drop_column('payment_screenshot_url')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('customer_email')

    # ### end Alembic commands ###
