"""Add must_change_password field to users

Revision ID: 3939abb5f84d
Revises: d8c050a4cad2
Create Date: 2026-01-04 21:39:31.984457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3939abb5f84d'
down_revision = 'd8c050a4cad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))
    
    # Set default value for existing users (False - they've already set passwords)
    op.execute("UPDATE users SET must_change_password = FALSE WHERE must_change_password IS NULL")
    
    # Now make it NOT NULL with default
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('must_change_password', nullable=False, server_default='false')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
